### ISSUE TITLE
add refinement capability to vtkPolyData

### ISSUE THREAD

**Issue by pletzer** [pletzer/icqsol#24]
When adding a field, and subsequently when colouring the field, we sometimes need to increase the resolution (that is decrease polygon sizes). We have a refineShape method, we need a refineVtkPolyData method that does the same on vtkPolyData objects.

We might consider a "refine" parameter passed to addSurfaceFieldFromExpression. We might as well consider a separate tool that refines.

**Comment by gregvonkuster** [comment]
The icqsol_refine_shape tool and the refine parameter added to the icqsol_add_surface_field_from_expression tool are available here:
https://git.psu.edu/axp5530/galaxy-web3d/commit/e198d1de11c13ed0abcc963e99880de2cdeb87f2

**Comment by pletzer** [comment]
I added a new method, refineVtkPolyData, to ShapeManager. There is a new examples/refineSurface script which will add points along the edges according to a max edge length criterion. I tested the script on the bolt shape and it seems to work fine. 

I think this is a better method than refineShape, which adds a point to the middle of the cells. If the cells are very elongated you will still get squashed triangles, not with refineVtkPolyData. icqsol_add_surface_field_from_expression should call this method prior to setting the field value.

**Comment by gregvonkuster** [comment]
I'll make this change.

**Comment by pletzer** [comment]
Here are the images
![testbolt](https://cloud.githubusercontent.com/assets/3027118/10093178/e4325d2a-631c-11e5-9e5e-16316ffcd064.png)
![testboltfine](https://cloud.githubusercontent.com/assets/3027118/10093182/f04e0410-631c-11e5-90a1-62a77d47fc80.png)
