### ISSUE TITLE
The Galaxy icqsol tool_dependencies.xml recipe fails subtly on Fedora 20

### ISSUE THREAD

**Issue by gregvonkuster** [pletzer/icqsol#26]
On Fedora 20, the recipe located here:
https://git.psu.edu/axp5530/galaxy-web3d/blob/master/galaxy/packages/package_icqsol_latest/tool_dependencies.xml

completes successfully within the Galaxy environment, but the INSTALLATION.LOG contains this error:

building 'bz2' extension
gcc -pthread -shared build/temp.linux-x86_64-2.7/home/greg/work/git_workspace/galaxy/database/tmp/tmp-toolshed-mtd0nrTzo/Python-2.7.10/Modules/bz2module.o -L/home/greg/work/ts_install/tool_dependency_dir/icqsol/latest/iuc/package_icqsol_latest/005863115a99/lib -L/usr/local/lib -L. -lbz2 -lpython2.7 -o build/lib.linux-x86_64-2.7/bz2.so

_curses            _curses_panel      _tkinter
bsddb185           dl                 imageop
readline           sunaudiodev
To find the necessary bits, look in setup.py in detect_modules() for the module's name.

Failed to build these modules:
bz2

The above failure to build Python with bz2 results in errors running the Galaxy tool wrappers for icqsol.

The following shows that bzip is available on the box when compiling Python.
$ yum list bzip2-devel
Loaded plugins: langpacks, refresh-packagekit
Available Packages
bzip2-devel.i686                        1.0.6-9.fc20                      fedora
bzip2-devel.x86_64                      1.0.6-9.fc20                      fedora

**Comment by pletzer** [comment]
Hi Greg,

Sounds like the modules that faield to compile are not critical.

--Alex

On Wed, Sep 16, 2015 at 3:10 PM, Greg Von Kuster <notifications@github.com>
wrote:

> On Fedora 20, the recipe located here:
>
> https://git.psu.edu/axp5530/galaxy-web3d/blob/master/galaxy/packages/package_icqsol_latest/tool_dependencies.xml
> completes successfully within the Galaxy environment, but the
> INSTALLATION.LOG contains this error:
>
> building 'bz2' extension
> gcc -pthread -shared
> build/temp.linux-x86_64-2.7/home/greg/work/git_workspace/galaxy/database/tmp/tmp-toolshed-mtd0nrTzo/Python-2.7.10/Modules/bz2module.o
> -L/home/greg/work/ts_install/tool_dependency_dir/icqsol/latest/iuc/package_icqsol_latest/005863115a99/lib
> -L/usr/local/lib -L. -lbz2 -lpython2.7 -o build/lib.linux-x86_64-2.7/bz2.so
>
> _curses _curses_panel _tkinter
> bsddb185 dl imageop
> readline sunaudiodev
> To find the necessary bits, look in setup.py in detect_modules() for the
> module's name.
>
> Failed to build these modules:
> bz2 The above failure to build Python with bz2 results in errors running
> the Galaxy tool wrappers for icqsol.
>
> The following shows that bzip is available on the box when compiling
> Python.
> $ yum list bzip2-devel
> Loaded plugins: langpacks, refresh-packagekit
> Available Packages
> bzip2-devel.i686 1.0.6-9.fc20 fedora
> bzip2-devel.x86_64 1.0.6-9.fc20 fedora
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pletzer/icqsol/issues/26>.
>



-- 
Alexander Pletzer
+1 609 799 7999 cell
alexander@gokliya.net

**Comment by gregvonkuster** [comment]
@pletzer The bz2 module is critical because the Python we compile for use to execute the Galaxy icqsol tools must be able to import bz2.  Since it cannot, the Galaxy icqsol tools result in errors when run on Linux.  We're currently depending on a bz2 module that is compiled static in our recipe, but our Python must be compiled with shared libraries.  So perhaps the fix is to change our recipe compile bz2 as shared, but I haven't yet tested this.  As you know, the current recipe works well on OS X, so the problem is restricted to Linux.

**Comment by gregvonkuster** [comment]
This issue is resolved as of this commit:
https://github.com/gregvonkuster/galaxy-csg/commit/8080fe9d7c7da39db226255c778fe2d46311334c

**Comment by pletzer** [comment]
Great!
