### ISSUE TITLE
Need to be able to load a file from disk and the internet

### ISSUE THREAD

**Issue by pletzer** [pletzer/icqsol#32]
There are many examples of ply and vtk files on the web, we should be able to load a geometry given a URL or file path.

**Comment by gregvonkuster** [comment]
Galaxy provides a means for doing this on the Get Data -> Upload file form.  There is an option on the bottom of the form labeled Paste / Fetch Data that allows for retrieving data via a URL.

**Comment by pletzer** [comment]
The version running on openshift was missing this section.
