### ISSUE TITLE
ShapeManager.addTextureToVtkPolyData() should accept an image format

### ISSUE THREAD

**Issue by gregvonkuster** [pletzer/icqsol#42]
Looking at a file name extension results in brittle code, and the method should accept an image format rather than looking at a file name extension.  If absolutely necessary, the method signature can set a default of None for the format, in which case the file system can be looked at if it is not passed, but this is still not optimal code.

**Comment by pletzer** [comment]
Hi Greg,

I disagree. I think the suffix determines the reader. The same principle is
used on Mac when you type the command "open <file>". Windows uses a similar
approach.

I could raise an exception...

On Tue, Dec 8, 2015 at 10:50 AM, Greg Von Kuster <notifications@github.com>
wrote:

> Looking at a file name extension results in brittle code, and the method
> should accept an image format rather than looking at a file name extension.
> If absolutely necessary, the method signature can set a default of None for
> the format, in which case the file system can be looked at if it is not
> passed, but this is still not optimal code.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pletzer/icqsol/issues/42>.
>



-- 
Alexander Pletzer
+1 609 799 7999 cell
alexander@gokliya.net

**Comment by gregvonkuster** [comment]
Hmmm....I guess we'll disagree on this one.  My opinion : OO programming allows for much more sophisticated coding practices than is generally available with OS commands, so just because OS X or Windows provides commands that inspect file extensions doesn't mean that that is the optimal approach..   Just a few examples with case sensitivity show problems - what happens if the file extension is JPEG, JPG or PNG or any combination of case?  Handling all cases of how a user may name a file creates non-optimal code with higher maintenance overhead.  The optimal solution is for a caller to be able to pass the file type to the receive, especially when the caller can discover the file format by actually inspecting it's contents like Galaxy does.  Then there is no question because there is no dependency on how a particular user chooses to name a file.  Why do you feel that it would be wrong to enhance the ShapeHanlder's method signature to accept a file type with the default set to None, something like format=None.  And only when the format is None is the file extension inspected?

**Comment by pletzer** [comment]
Done
