### ISSUE TITLE
ShapeManager.addTextureToVtkPolyData() throws exception

### ISSUE THREAD

**Issue by gregvonkuster** [pletzer/icqsol#43]
ERROR: 
"/Users/gvk/work/ts_install/shed_tools/localhost/repos/iuc/icqsol_add_texture/3a5d2cc28450/icqsol_add_texture/icqsol_add_texture.py", line 38, in <module>
    max_edge_length=args.max_edge_length)
  File "build/bdist.macosx-10.5-x86_64/egg/icqsol/shapes/icqShapeManager.py", line 215, in addTextureToVtkPolyData
TypeError: SetTuple argument 2: expected a sequence of 3 values, got 1 values

**Comment by pletzer** [comment]
Greg,

Can you tell me how you got the error? I was not able to get this error
with any of the three texture files under textures/ (?)

Were you using a black and white image?

--Alex



On Tue, Dec 8, 2015 at 11:49 AM, Greg Von Kuster <notifications@github.com>
wrote:

> ERROR:
> "/Users/gvk/work/ts_install/shed_tools/localhost/repos/iuc/icqsol_add_texture/3a5d2cc28450/icqsol_add_texture/icqsol_add_texture.py",
> line 38, in
> max_edge_length=args.max_edge_length)
> File
> "build/bdist.macosx-10.5-x86_64/egg/icqsol/shapes/icqShapeManager.py", line
> 215, in addTextureToVtkPolyData
> TypeError: SetTuple argument 2: expected a sequence of 3 values, got 1
> values
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pletzer/icqsol/issues/43>.
>



-- 
Alexander Pletzer
+1 609 799 7999 cell
alexander@gokliya.net

**Comment by gregvonkuster** [comment]
I get this running the Galaxy tool where the shape is our shaft.vtkascii test-data file and the texture is the conglomerateSandstone.jpg.  Running the same job again, I noticed more login for the exception - the full exception is this.  Possibly this is because the file extension does not have a "." before the jpg.  Let me see if I can fix this at my end.

ERROR: In /Users/gvk/work/git_workspace/galaxy/database/tmp/tmp-toolshed-mtdKpVgTi/vtk/VTK-6.2.0/IO/Image/vtkJPEGReader.cxx, line 174
vtkJPEGReader (0x105a55dd0): libjpeg could not read file: /var/folders/qm/p6jt97wj4239jx8gdv7jy75m0000gn/T/tmp-vtk-X0NDTf/tmpB1egH6jpg

ERROR: In /Users/gvk/work/git_workspace/galaxy/database/tmp/tmp-toolshed-mtdKpVgTi/vtk/VTK-6.2.0/IO/Image/vtkJPEGReader.cxx, line 357
vtkJPEGReader (0x105a55dd0): libjpeg could not read file: /var/folders/qm/p6jt97wj4239jx8gdv7jy75m0000gn/T/tmp-vtk-X0NDTf/tmpB1egH6jpg

Traceback (most recent call last):
  File "/Users/gvk/work/ts_install/shed_tools/localhost/repos/iuc/icqsol_add_texture/3a5d2cc28450/icqsol_add_texture/icqsol_add_texture.py", line 38, in <module>
    max_edge_length=args.max_edge_length)
  File "build/bdist.macosx-10.5-x86_64/egg/icqsol/shapes/icqShapeManager.py", line 215, in addTextureToVtkPolyData
TypeError: SetTuple argument 2: expected a sequence of 3 values, got 1 values

**Comment by gregvonkuster** [comment]
Still getting an exception, even when the file name ends with .jpg:

ERROR: In /Users/gvk/work/git_workspace/galaxy/database/tmp/tmp-toolshed-mtdKpVgTi/vtk/VTK-6.2.0/IO/Image/vtkJPEGReader.cxx, line 174
vtkJPEGReader (0x10230dc80): libjpeg could not read file: /var/folders/qm/p6jt97wj4239jx8gdv7jy75m0000gn/T/tmp-vtk-0pMPyL/tmp_lWj1O.jpg

ERROR: In /Users/gvk/work/git_workspace/galaxy/database/tmp/tmp-toolshed-mtdKpVgTi/vtk/VTK-6.2.0/IO/Image/vtkJPEGReader.cxx, line 357
vtkJPEGReader (0x10230dc80): libjpeg could not read file: /var/folders/qm/p6jt97wj4239jx8gdv7jy75m0000gn/T/tmp-vtk-0pMPyL/tmp_lWj1O.jpg

Traceback (most recent call last):
  File "/Users/gvk/work/ts_install/shed_tools/localhost/repos/iuc/icqsol_add_texture/3a5d2cc28450/icqsol_add_texture/icqsol_add_texture.py", line 38, in <module>
    max_edge_length=args.max_edge_length)
  File "build/bdist.macosx-10.5-x86_64/egg/icqsol/shapes/icqShapeManager.py", line 215, in addTextureToVtkPolyData
TypeError: SetTuple argument 2: expected a sequence of 3 values, got 1 values

**Comment by gregvonkuster** [comment]
@pletzer I'm also bumping into this exception - does /icqRefineSurface.py", line 95 need to be float()?

ERROR: In /Users/gvk/work/git_workspace/galaxy/database/tmp/tmp-toolshed-mtdKpVgTi/vtk/VTK-6.2.0/IO/Image/vtkJPEGReader.cxx, line 174
vtkJPEGReader (0x1021e1d30): libjpeg could not read file: /var/folders/qm/p6jt97wj4239jx8gdv7jy75m0000gn/T/tmp-vtk-G60Quf/tmperd0F4.jpg

ERROR: In /Users/gvk/work/git_workspace/galaxy/database/tmp/tmp-toolshed-mtdKpVgTi/vtk/VTK-6.2.0/IO/Image/vtkJPEGReader.cxx, line 357
vtkJPEGReader (0x1021e1d30): libjpeg could not read file: /var/folders/qm/p6jt97wj4239jx8gdv7jy75m0000gn/T/tmp-vtk-G60Quf/tmperd0F4.jpg

/Users/gvk/work/ts_install/tool_dependency_dir/icqsol/1.0/iuc/package_icqsol_1_0/19f4aac37954/lib/python2.7/site-packages/icqsol-0.2.3-py2.7.egg/icqsol/shapes/icqRefineSurface.py:95: RuntimeWarning: divide by zero encountered in double_scalars
Traceback (most recent call last):
  File "/Users/gvk/work/ts_install/shed_tools/localhost/repos/iuc/icqsol_add_texture/3a5d2cc28450/icqsol_add_texture/icqsol_add_texture.py", line 38, in <module>
    max_edge_length=args.max_edge_length)
  File "build/bdist.macosx-10.5-x86_64/egg/icqsol/shapes/icqShapeManager.py", line 202, in addTextureToVtkPolyData
  File "build/bdist.macosx-10.5-x86_64/egg/icqsol/shapes/icqShapeManager.py", line 410, in refineVtkPolyData
  File "build/bdist.macosx-10.5-x86_64/egg/icqsol/shapes/icqRefineSurface.py", line 95, in refine
OverflowError: cannot convert float infinity to integer

**Comment by gregvonkuster** [comment]
This commit https://github.com/gregvonkuster/galaxy-csg/commit/2644dfa48234349945e88cf7b383665692ac315b corrected the behavior described in this issue, so closing.

**Comment by pletzer** [comment]
Greg,

The error says that libjpeg could not open the file. What file is this?

--Alex

On Tue, Dec 8, 2015 at 7:43 PM, Greg Von Kuster <notifications@github.com>
wrote:

> I get this running the Galaxy tool where the shape is our shaft.vtkascii
> test-data file and the texture is the conglomerateSandstone.jpg. Running
> the same job again, I noticed more login for the exception - the full
> exception is this. Possibly this is because the file extension does not
> have a "." before the jpg. Let me see if I can fix this at my end.
>
> ERROR: In
> /Users/gvk/work/git_workspace/galaxy/database/tmp/tmp-toolshed-mtdKpVgTi/vtk/VTK-6.2.0/IO/Image/vtkJPEGReader.cxx,
> line 174
> vtkJPEGReader (0x105a55dd0): libjpeg could not read file:
> /var/folders/qm/p6jt97wj4239jx8gdv7jy75m0000gn/T/tmp-vtk-X0NDTf/tmpB1egH6jpg
>
> ERROR: In
> /Users/gvk/work/git_workspace/galaxy/database/tmp/tmp-toolshed-mtdKpVgTi/vtk/VTK-6.2.0/IO/Image/vtkJPEGReader.cxx,
> line 357
> vtkJPEGReader (0x105a55dd0): libjpeg could not read file:
> /var/folders/qm/p6jt97wj4239jx8gdv7jy75m0000gn/T/tmp-vtk-X0NDTf/tmpB1egH6jpg
>
> Traceback (most recent call last):
> File
> "/Users/gvk/work/ts_install/shed_tools/localhost/repos/iuc/icqsol_add_texture/3a5d2cc28450/icqsol_add_texture/icqsol_add_texture.py",
> line 38, in
> max_edge_length=args.max_edge_length)
> File
> "build/bdist.macosx-10.5-x86_64/egg/icqsol/shapes/icqShapeManager.py", line
> 215, in addTextureToVtkPolyData
> TypeError: SetTuple argument 2: expected a sequence of 3 values, got 1
> values
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pletzer/icqsol/issues/43#issuecomment-163088651>.
>



-- 
Alexander Pletzer
+1 609 799 7999 cell
alexander@gokliya.net

**Comment by pletzer** [comment]
Greg,

I see the error but I think it is related to not being able to open the
temporary jpg file. I don't understand that piece of the code so will let
you fix.

--Alex

Tech-Xs-MacBook-Pro:test-data pletzer$ python ../icqsol_add_texture.py
--input shaft.vtkascii --input_file_format_and_type vtkascii
--input_dataset_type POLYDATA --input_texture sandstone.jpg
--max_edge_length 0.1 --output shaft_with_texture.vtkascii
--output_vtk_type vtkascii --input_texture_file_format jpg

ERROR: In -------src-dir--------/VTK5.10.1/IO/vtkJPEGReader.cxx, line 93

vtkJPEGReader (0x10038fc60): Unable to open file
/var/folders/z6/6mrzrhhs7kdbgkpfct2225d40000gp/T/tmp-vtk-srk0tg/tmpN4BsKS.jpg


Traceback (most recent call last):

  File "../icqsol_add_texture.py", line 47, in <module>

    max_edge_length=args.max_edge_length)

  File
"build/bdist.macosx-10.5-x86_64/egg/icqsol/shapes/icqShapeManager.py", line
215, in addTextureToVtkPolyData

TypeError: argument 2: expected a sequence of 3 values, got 1 values

On Wed, Dec 9, 2015 at 3:32 PM, Alexander Pletzer <alexander@gokliya.net>
wrote:

> Greg,
>
> The error says that libjpeg could not open the file. What file is this?
>
> --Alex
>
> On Tue, Dec 8, 2015 at 7:43 PM, Greg Von Kuster <notifications@github.com>
> wrote:
>
>> I get this running the Galaxy tool where the shape is our shaft.vtkascii
>> test-data file and the texture is the conglomerateSandstone.jpg. Running
>> the same job again, I noticed more login for the exception - the full
>> exception is this. Possibly this is because the file extension does not
>> have a "." before the jpg. Let me see if I can fix this at my end.
>>
>> ERROR: In
>> /Users/gvk/work/git_workspace/galaxy/database/tmp/tmp-toolshed-mtdKpVgTi/vtk/VTK-6.2.0/IO/Image/vtkJPEGReader.cxx,
>> line 174
>> vtkJPEGReader (0x105a55dd0): libjpeg could not read file:
>> /var/folders/qm/p6jt97wj4239jx8gdv7jy75m0000gn/T/tmp-vtk-X0NDTf/tmpB1egH6jpg
>>
>> ERROR: In
>> /Users/gvk/work/git_workspace/galaxy/database/tmp/tmp-toolshed-mtdKpVgTi/vtk/VTK-6.2.0/IO/Image/vtkJPEGReader.cxx,
>> line 357
>> vtkJPEGReader (0x105a55dd0): libjpeg could not read file:
>> /var/folders/qm/p6jt97wj4239jx8gdv7jy75m0000gn/T/tmp-vtk-X0NDTf/tmpB1egH6jpg
>>
>> Traceback (most recent call last):
>> File
>> "/Users/gvk/work/ts_install/shed_tools/localhost/repos/iuc/icqsol_add_texture/3a5d2cc28450/icqsol_add_texture/icqsol_add_texture.py",
>> line 38, in
>> max_edge_length=args.max_edge_length)
>> File
>> "build/bdist.macosx-10.5-x86_64/egg/icqsol/shapes/icqShapeManager.py", line
>> 215, in addTextureToVtkPolyData
>> TypeError: SetTuple argument 2: expected a sequence of 3 values, got 1
>> values
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/pletzer/icqsol/issues/43#issuecomment-163088651>.
>>
>
>
>
> --
> Alexander Pletzer
> +1 609 799 7999 cell
> alexander@gokliya.net
>



-- 
Alexander Pletzer
+1 609 799 7999 cell
alexander@gokliya.net

**Comment by gregvonkuster** [comment]
@pletzer This issue has been handled and closed....
