### ISSUE TITLE
RefineSurface.refine() function throws exception

### ISSUE THREAD

**Issue by gregvonkuster** [pletzer/icqsol#44]
/Users/gvk/work/ts_install/tool_dependency_dir/icqsol/1.0/iuc/package_icqsol_1_0/19f4aac37954/lib/python2.7/site-packages/icqsol-0.2.3-py2.7.egg/icqsol/shapes/icqRefineSurface.py:95: RuntimeWarning: divide by zero encountered in double_scalars
Traceback (most recent call last):
  File "/Users/gvk/work/ts_install/shed_tools/localhost/repos/iuc/icqsol_add_texture/3a5d2cc28450/icqsol_add_texture/icqsol_add_texture.py", line 40, in <module>
    max_edge_length=args.max_edge_length)
  File "build/bdist.macosx-10.5-x86_64/egg/icqsol/shapes/icqShapeManager.py", line 202, in addTextureToVtkPolyData
  File "build/bdist.macosx-10.5-x86_64/egg/icqsol/shapes/icqShapeManager.py", line 410, in refineVtkPolyData
  File "build/bdist.macosx-10.5-x86_64/egg/icqsol/shapes/icqRefineSurface.py", line 95, in refine
OverflowError: cannot convert float infinity to integer

**Comment by pletzer** [comment]
PR #22 should fix this, let me know if not. Thanks.

--Alex

On Wed, Dec 9, 2015 at 7:04 AM, Greg Von Kuster <notifications@github.com>
wrote:

> /Users/gvk/work/ts_install/tool_dependency_dir/icqsol/1.0/iuc/package_icqsol_1_0/19f4aac37954/lib/python2.7/site-packages/icqsol-0.2.3-py2.7.egg/icqsol/shapes/icqRefineSurface.py:95:
> RuntimeWarning: divide by zero encountered in double_scalars
> Traceback (most recent call last):
> File
> "/Users/gvk/work/ts_install/shed_tools/localhost/repos/iuc/icqsol_add_texture/3a5d2cc28450/icqsol_add_texture/icqsol_add_texture.py",
> line 40, in
> max_edge_length=args.max_edge_length)
> File
> "build/bdist.macosx-10.5-x86_64/egg/icqsol/shapes/icqShapeManager.py", line
> 202, in addTextureToVtkPolyData
> File
> "build/bdist.macosx-10.5-x86_64/egg/icqsol/shapes/icqShapeManager.py", line
> 410, in refineVtkPolyData
> File
> "build/bdist.macosx-10.5-x86_64/egg/icqsol/shapes/icqRefineSurface.py",
> line 95, in refine
> OverflowError: cannot convert float infinity to integer
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pletzer/icqsol/issues/44>.
>



-- 
Alexander Pletzer
+1 609 799 7999 cell
alexander@gokliya.net

**Comment by gregvonkuster** [comment]
@pletzer The fix needs to be handled here, not in the caller which should be able to send the default float('inf') to this code.

**Comment by pletzer** [comment]
@gregvonkuster 

The problem is that the default value is set to 0.0. Ideally, the default value should be 'inf' 
but this may not be practical or feasible within the galaxy GUI. So 0 may be used to represent infinity. If so then the logic will have to be handled by icqsol_add_texture since this is a limitation of the galaxy gui (addTexture in icqsol is happy to take float('inf') as value). 

<param name="max_edge_length" type="float" value="0.0" optional="True" label="Maximum edge length" help="Optionally refine shape by restricting edges to this length (zero value results in no refinement).">
            <validator type="in_range" min="0" exclude_min="true" />

**Comment by pletzer** [comment]
@gregvonkuster The default value is 0 but this values is no longer allowed.

**Comment by pletzer** [comment]
The description "(zero value results in no refinement)" should be corrected to "(a very large value results in no refinement)".

**Comment by gregvonkuster** [comment]
@pletzer Should the value of 0 be allowed?  Is it realistic to have an edge length of 0?  Also, if the statement "(zero value results in no refinement)" is changed to "(a very large value results in no refinement)", the statement becomes unclear.  What is "a very large value"?  If a length of 0 should be allowed, then I'll just eliminate the statement altogether.

**Comment by pletzer** [comment]
@gregvonkuster As mentioned previously, max_edge_length should be > 0. 

I would do the same as for the refinement tool. Have a yes/no box to select whether refinement is desired. If Yes is selected (default should be no) then enforce max_edge_length to be > 0.

**Comment by gregvonkuster** [comment]
@pletzer Which tool are you talking about here?

**Comment by pletzer** [comment]
@gregvonkuster Add surface field from expression

**Comment by pletzer** [comment]
Fixed (I think)
